const $$=s=>[...document.querySelectorAll(s)],$=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {portalLogin,changePortalPin,portalLogout,portalGetBundle,registerPortalPush,WEB_PUSH_VAPID_PUBLIC_KEY} from '../shared/supabase-adapter.js?v=810';
let id='',bundle=null,currentToken='',scanner=null,familySWRegistration=null;
function setView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
async function ensureSW(){if(!('serviceWorker'in navigator))return null;familySWRegistration=await navigator.serviceWorker.register('./service-worker.js?v=814',{scope:'./'});return navigator.serviceWorker.ready}
function vapidBytes(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from([...atob(b)].map(c=>c.charCodeAt(0)))}
async function syncPush(){if(!currentToken||!('Notification'in window)||Notification.permission!=='granted')return;const reg=familySWRegistration||await ensureSW();let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:vapidBytes(WEB_PUSH_VAPID_PUBLIC_KEY)});await registerPortalPush(currentToken,sub);localStorage.setItem(`familyPushRegistered:${id}`,'1');updatePush()}
function updatePush(){const e=$('#familyPushStatus');if(!e)return;e.textContent=Notification.permission==='granted'&&localStorage.getItem(`familyPushRegistered:${id}`)==='1'?'✓ Este dispositivo está registrado para recibir notificaciones push.':Notification.permission==='denied'?'Las notificaciones están bloqueadas en este dispositivo.':'Las notificaciones todavía no están activadas en este dispositivo.'}
async function enableNotifications(){try{await ensureSW();let p=Notification.permission;if(p!=='granted')p=await Notification.requestPermission();if(p!=='granted')throw new Error('No se concedió permiso para notificaciones.');await syncPush();alert('Notificaciones activadas correctamente.')}catch(e){alert('No se pudo activar las notificaciones: '+(e.message||e))}}
function saveSession(r){const d=JSON.stringify({studentId:id,role:'parent',token:currentToken});(r?localStorage:sessionStorage).setItem('familySession',d)}function clearSession(){localStorage.removeItem('familySession');sessionStorage.removeItem('familySession')}
async function doLogin(){const sid=$('#loginId').value.trim(),pin=$('#loginPin').value.trim(),er=$('#loginError');er.textContent='';if(!sid||!pin){er.textContent='Escribe el ID del alumno y tu PIN.';return}try{const r=await portalLogin(sid,'parent',pin,$('#rememberSession').checked);if(!r.ok){er.textContent=r.reason==='locked'?'Has excedido el número de intentos permitidos. Intenta nuevamente en 10 minutos.':r.reason==='shift'?'Seguimiento Familiar solo está disponible para el turno matutino.':r.reason==='not_provisioned'?'El acceso familiar todavía no ha sido preparado por el profesor.':'ID o PIN incorrecto.';return}id=sid;currentToken=r.token;if(r.must_change){await forceChangePin();return}saveSession($('#rememberSession').checked);await enterPortal()}catch(e){er.textContent='No se pudo conectar con el sistema. Revisa tu internet e intenta nuevamente.'}}
async function forceChangePin(){const remember=$('#rememberSession')?.checked||false;$('#loginGate').innerHTML=`<div class="login-card"><h2>Bienvenido</h2><p>Por seguridad debes crear un PIN personal para la familia.</p><label>Nuevo PIN<input id="newPersonalPin" type="password" inputmode="numeric" maxlength="8"></label><label>Confirmar PIN<input id="confirmPersonalPin" type="password" inputmode="numeric" maxlength="8"></label><button id="savePersonalPin" class="action">Guardar nuevo PIN</button><div id="changePinError" class="login-error"></div></div>`;$('#savePersonalPin').onclick=async()=>{let a=$('#newPersonalPin').value.trim(),b=$('#confirmPersonalPin').value.trim();if(!/^\d{4,8}$/.test(a))return $('#changePinError').textContent='El PIN debe tener de 4 a 8 números.';if(a!==b)return $('#changePinError').textContent='Los PIN no coinciden.';let r=await changePortalPin(currentToken,a);if(!r?.ok)return $('#changePinError').textContent='No se pudo guardar el PIN.';saveSession(remember);await enterPortal()}}
async function enterPortal(){try{const raw=await Promise.race([portalGetBundle(currentToken),new Promise((_,rej)=>setTimeout(()=>rej(new Error('TIMEOUT')),5000))]);if(!raw?.ok){clearSession();return false}bundle=raw;id=bundle.student.id;$('#sessionLoading').classList.add('hidden');$('#loginGate').classList.add('hidden');$('#portalApp').classList.remove('hidden');$('#familyHello').textContent=`Familia de ${bundle.student.name||'alumno'}`;renderAll();await updateContact();updatePush();if(Notification.permission==='granted')syncPush().catch(()=>{});return true}catch(e){$('#sessionLoading').classList.add('hidden');$('#loginGate').classList.remove('hidden');return false}}
async function logout(){try{if(currentToken)await portalLogout(currentToken)}catch(e){}clearSession();location.reload()}
async function startScanner(){if(typeof Html5Qrcode==='undefined')return $('#loginError').textContent='No fue posible cargar el lector. Puedes escribir el ID manualmente.';scanner=new Html5Qrcode('barcodeReader');try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:280,height:120}},d=>{$('#loginId').value=d;stopScanner()},()=>{})}catch(e){$('#loginError').textContent='No se pudo abrir la cámara.'}}
async function stopScanner(){if(scanner){try{await scanner.stop();await scanner.clear()}catch(e){}scanner=null}}
function grade(){let l=(bundle?.methodologies||[]).filter(m=>m.closed&&m.gradeRecords?.[id]?.finalDecimal!=null).sort((a,b)=>String(b.closedAt||b.updated||'').localeCompare(String(a.closedAt||a.updated||'')));return l[0]?.gradeRecords?.[id]||null}
function portalDate(v){if(!v)return'Sin fecha';let d=new Date(v+'T12:00:00');return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('es-MX',{day:'numeric',month:'long'})}
function activityState(a,r){if((a.evaluationMode||'delivery')==='numeric'&&typeof r?.score==='number')return{label:'Entregada',cls:'ok'};if(r?.status==='yes')return{label:'Entregada',cls:'ok'};if(r?.status==='no')return{label:'No entregada',cls:'bad'};if(a.dueDate&&new Date(a.dueDate+'T23:59:59')<new Date())return{label:'Vencida',cls:'bad'};return{label:'Pendiente',cls:'warn'}}
function areaInfo(raw){const k=String(raw||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();const m={
'area i':['Hábitos para estudiar','Forma en que el alumno organiza y realiza el estudio: lectura, repaso, atención a la información y estrategias para aprender.'],'area ii':['Realización de tareas','Hábitos relacionados con el cumplimiento de tareas, organización del trabajo, revisión y responsabilidad al realizarlas.'],'area iii':['Preparación para exámenes','Forma en que el alumno se organiza, repasa y distribuye el tiempo para prepararse antes de una evaluación.'],'area iv':['Atención y aprovechamiento de las clases','Hábitos para escuchar, atender explicaciones, identificar ideas importantes y aprovechar el trabajo realizado durante la clase.'],'area v':['Condiciones que acompañan el estudio','Factores que rodean el momento de estudiar, como organización del espacio, distractores, materiales y condiciones que favorecen o dificultan el trabajo.'],'mayusculas':['Uso de mayúsculas','Aplicación adecuada de mayúsculas al inicio de oraciones, en nombres propios y en otros casos que lo requieren.'],'ortografia arbitraria':['Ortografía de palabras de uso frecuente','Escritura correcta de palabras cuya ortografía se aprende principalmente mediante lectura, memoria visual y práctica.'],'pseudopalabras':['Relación entre sonidos y escritura','Capacidad para representar correctamente por escrito una secuencia de sonidos, incluso cuando se trata de palabras nuevas.'],'reglas ortograficas en pseudopalabras':['Aplicación de reglas ortográficas','Uso de reglas ortográficas al escribir palabras nuevas o poco familiares.'],'razonamiento':['Razonamiento','Capacidad para analizar información, encontrar relaciones entre ideas y utilizar lo aprendido para resolver situaciones nuevas.'],'reflexion evaluacion':['Comprensión y reflexión sobre lo leído','Capacidad para interpretar información, justificar respuestas, relacionar ideas y valorar el contenido o la forma de un texto.'],'recuperacion de informacion':['Localización de información en textos','Capacidad para encontrar datos, ideas y detalles que aparecen de manera explícita en una lectura.'],'integracion de informacion':['Integración de información','Capacidad para relacionar distintas partes de un texto y construir una comprensión global.'],'redaccion':['Expresión escrita','Capacidad para organizar, desarrollar y comunicar ideas por escrito de manera clara y comprensible.']};let x=m[k];if(!x){if(k.includes('mayus'))x=m.mayusculas;else if(k.includes('ortograf')&&k.includes('arbitr'))x=m['ortografia arbitraria'];else if(k.includes('pseudo')&&k.includes('regla'))x=m['reglas ortograficas en pseudopalabras'];else if(k.includes('pseudo'))x=m.pseudopalabras;else if(k.includes('razon'))x=m.razonamiento;else if(k.includes('reflex')||k.includes('evaluac'))x=m['reflexion evaluacion'];else if(k.includes('recuper'))x=m['recuperacion de informacion'];else if(k.includes('integr'))x=m['integracion de informacion'];else if(k.includes('redac'))x=m.redaccion}return{title:x?.[0]||raw||'Resultado',detail:x?.[1]||String(raw||'')}}
function diagnosticObject(){
 const roots=[bundle,bundle?.data,bundle?.result,bundle?.studentBundle,bundle?.student_bundle].filter(Boolean);
 let candidates=[];
 for(const r of roots){
  candidates.push(
   r?.publishedDiagnostic,r?.published_diagnostic,r?.diagnosticPublication,r?.diagnostic_publication,
   r?.diagnosticResult,r?.diagnostic_result,r?.initialDiagnostic,r?.initial_diagnostic,r?.diagnostic,
   r?.publishedDiagnostics,r?.published_diagnostics,r?.diagnosticResults,r?.diagnostic_results,r?.diagnostics
  );
 }
 candidates=candidates.flatMap(c=>Array.isArray(c)?c:[c]).filter(Boolean);
 const hasContent=d=>!!(
  d?.synthesis||d?.integrated_synthesis||d?.technical||d?.integrated_technical||
  d?.published_result||d?.publishedResult||d?.result?.synthesis||d?.data?.synthesis||
  d?.strengths||d?.support_areas||d?.supportAreas||d?.recommendations||d?.recomendaciones
 );
 const isPublished=d=>d?.published===true||d?.visible===true||d?.is_published===true||d?.isPublished===true||
  d?.publication?.published===true||!!d?.published_at||!!d?.publishedAt||!!d?.publication?.published_at;
 return candidates.find(d=>isPublished(d)&&hasContent(d))
     || candidates.find(d=>isPublished(d))
     || candidates.find(d=>hasContent(d)&&d?.published!==false&&d?.visible!==false&&d?.is_published!==false)
     || null;
}
function synthesisFrom(d){return d?.synthesis||d?.integrated_synthesis||d?.result?.synthesis||d?.data?.synthesis||d?.published_result?.synthesis||d||{}}
function technicalFrom(d){return d?.technical||d?.integrated_technical||d?.result?.technical||d?.data?.technical||d?.published_result?.technical||{}}
function friendlyItem(o,section){const area=o?.displayArea||o?.area||o?.title||o?.name||'',info=areaInfo(area),src=String(o?.source||'').toUpperCase(),raw=String(o?.displayText||o?.text||o?.description||'').trim();let text=raw||info.detail;if(section==='strength'){if(src.includes('SAGES')&&/aptitud sobresaliente/i.test(raw)){const q=raw.match(/percentil\s+(\d+(?:\.\d+)?)/i);text=`Se identifica una aptitud sobresaliente en ${info.title}${q?` (percentil ${q[1]})`:''}.`}else if(src.includes('CASM'))text=`${info.detail} En este diagnóstico se observa como una fortaleza.`;else if(src.includes('PROESC'))text=`${info.detail} En este diagnóstico se observa un desempeño favorable.`;else if(src.includes('COMPLEC'))text=`${info.detail} Este proceso se ubica entre sus fortalezas de comprensión lectora.`}else if(section==='support')text=`Conviene reforzar ${info.detail.charAt(0).toLowerCase()+info.detail.slice(1)}`;return{title:info.title,text}}
function diagList(items,section,empty){if(!Array.isArray(items)||!items.length)return`<div class="muted">${esc(empty)}</div>`;return`<div class="diag-list">${items.map(i=>{let x=friendlyItem(i,section);return`<div class="diag-item"><b>${esc(x.title)}</b><p>${esc(x.text)}</p></div>`}).join('')}</div>`}
function renderDiagnostic(){const box=$('#familyDiagnostic');if(!box)return;const d=diagnosticObject();if(!d){box.innerHTML='<div class="card muted">El diagnóstico inicial todavía no ha sido publicado por el profesor.</div>';return}const syn=synthesisFrom(d),tech=technicalFrom(d);let strengths=Array.isArray(syn.strengths)?syn.strengths.map(x=>({...x})):[];const sg=tech?.sages||d?.sages||{};[['language','Lengua y literatura / Ciencias sociales'],['reasoning','Razonamiento']].forEach(([k,label])=>{const p=Number(sg?.[k]?.percentile);if(Number.isFinite(p)&&p>=90&&!strengths.some(x=>String(x.text||'').toLowerCase().includes('aptitud sobresaliente')&&String(x.area||'').toLowerCase().includes(label.toLowerCase().split(' ')[0])))strengths.unshift({area:label,text:`Se identifica aptitud sobresaliente en ${label} (percentil ${p}).`,source:'SAGES-2'})});const support=syn.support_areas||syn.supportAreas||syn.areas_to_reinforce||[],recs=syn.recommendations||syn.recomendaciones||[];box.innerHTML=`<div class="diagnostic-shell"><div class="diag-hero"><h3>Resultado del diagnóstico inicial</h3><p>Este diagnóstico muestra el punto de partida del alumno al inicio del ciclo escolar. Permite reconocer lo que ya realiza favorablemente y los aspectos que conviene acompañar durante las clases de Español.</p></div><section class="diag-section"><div class="diag-title"><div class="icon">✓</div><div><h3>Fortalezas</h3><p>Aspectos que se observan favorablemente.</p></div></div>${diagList(strengths,'strength','En este momento no se identificaron fortalezas específicas para destacar.')}</section><section class="diag-section"><div class="diag-title"><div class="icon">↗</div><div><h3>Aspectos por reforzar</h3><p>Habilidades que conviene seguir trabajando.</p></div></div>${diagList(support,'support','En este momento no se identificaron aspectos específicos que requieran refuerzo.')}</section><section class="diag-section"><div class="diag-title"><div class="icon">★</div><div><h3>Recomendaciones</h3><p>Sugerencias para acompañar su aprendizaje.</p></div></div>${diagList(recs,'recommendation','No se generaron recomendaciones específicas.')}</section><div class="diag-note"><b>Importante</b><br>Este resultado es informativo y pedagógico. No representa una calificación y no constituye un diagnóstico clínico ni psicológico.</div></div>`}
function renderAll(){let g=grade(),att=bundle.attendance||[],map=new Map((bundle.activityRecords||[]).map(r=>[r.key,r]));let pending=(bundle.activities||[]).filter(a=>['Pendiente','Vencida','No entregada'].includes(activityState(a,map.get(`${a.id}|${id}`)).label)).length;$('#familyStats').innerHTML=[['Asistencia',att.length],['Pendientes',pending],['Promedio',g?.finalDecimal?.toFixed(2)||'—'],['Avisos',(bundle.notices||[]).length]].map(x=>`<div class="stat-card"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('#familyNotice').innerHTML=(bundle.notices||[]).slice(0,2).map(n=>`<div class="notice"><b>${esc(n.title)}</b><p>${esc(n.text)}</p></div>`).join('')||'<div class="notice muted">Sin avisos recientes.</div>';$('#familyNotices').innerHTML=(bundle.notices||[]).map(n=>`<div class="card"><b>${esc(n.title)}</b><p>${esc(n.text)}</p></div>`).join('')||'<div class="card muted">Sin avisos.</div>';$('#familyMaterials').innerHTML=(bundle.materials||[]).map(m=>`<div class="card"><b>${esc(m.title)}</b>${m.publicUrl||m.url?`<button class="action material-open" data-url="${esc(m.publicUrl||m.url)}">Abrir material</button>`:''}</div>`).join('')||'<div class="card muted">Sin materiales.</div>';$$('.material-open').forEach(b=>b.onclick=()=>window.open(b.dataset.url,'_blank'));$('#familyAttendance').innerHTML=att.length?att.sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,40).map(a=>`<div class="card"><b>${esc(a.date)}</b> <span class="status ${a.status==='Falta'?'bad':a.status==='Retardo'?'warn':'ok'}">${esc(a.status||'Presente')}</span></div>`).join(''):'<div class="card muted">Sin registros.</div>';let acts=[...(bundle.activities||[])].sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'));$('#familyActivities').innerHTML=acts.map(a=>{let r=map.get(`${a.id}|${id}`),s=activityState(a,r);return`<div class="card"><div class="delivery-title">${esc(a.name)}</div><div class="delivery-line"><b>Asignada:</b> ${esc(portalDate(a.date))}</div><div class="delivery-line"><b>Entrega:</b> ${esc(portalDate(a.dueDate))}</div><div class="delivery-line"><b>Estado:</b> <span class="status ${s.cls}">${s.label}</span></div>${typeof r?.score==='number'?`<div><b>Calificación:</b> ${r.score}/10</div>`:''}</div>`}).join('')||'<div class="card muted">No hay próximas entregas publicadas.</div>';$('#familyGrades').innerHTML=`<div class="card"><h3>Promedio actual</h3><h1>${g?.finalDecimal?.toFixed(2)||'—'}</h1><p>Calificación redondeada: <b>${g?.rounded??'—'}</b></p></div>`;$('#familyReports').innerHTML=(bundle.reports||[]).map(r=>`<button class="big-button"><b>PDF</b><span>${esc(r.title)}</span></button>`).join('')||'<div class="card muted">Sin reportes disponibles.</div>';renderDiagnostic()}
async function isAvailable(){let a=bundle.availability||{},now=new Date(),date=now.toISOString().slice(0,10),hm=now.toTimeString().slice(0,5),vac=a.vacationStart&&a.vacationEnd&&date>=a.vacationStart&&date<=a.vacationEnd;return{a,open:!a.suspended&&!vac&&!(a.technicalCouncilDates||[]).includes(date)&&(a.days||[]).includes(now.getDay())&&hm>=(a.start||'12:00')&&hm<=(a.end||'15:00')}}async function updateContact(){let{a,open}=await isAvailable();$('#contactSchedule').textContent=`Horario de atención: lunes a viernes, ${a.start||'12:00'} a ${a.end||'15:00'}.`;$('#contactTeacher').disabled=!open;$('#contactMessage').textContent=open?'El botón está disponible dentro del horario de atención.':'Los mensajes enviados fuera del horario de atención serán respondidos el siguiente día hábil.'}async function openWhatsApp(){let{open}=await isAvailable();if(!open)return updateContact();let s=bundle.student,msg=`Buenas tardes, profesor Jaime.%0A%0ASoy el padre/madre de ${encodeURIComponent(s.name||'')} del grupo ${encodeURIComponent(s.group||'')}.%0A%0AMe comunico para realizar la siguiente consulta:%0A`;window.open(`https://wa.me/?text=${msg}`,'_blank')}
async function init(){ensureSW().catch(()=>{});$('#loginBtn').onclick=doLogin;$('#logoutBtn').onclick=logout;$('#scanIdBtn').onclick=startScanner;$('#stopScanBtn').onclick=stopScanner;$('#contactTeacher').onclick=openWhatsApp;$('#enableFamilyNotif').onclick=enableNotifications;const saved=localStorage.getItem('familySession')||sessionStorage.getItem('familySession');if(saved){try{let s=JSON.parse(saved);id=s.studentId;currentToken=s.token||'';if(currentToken&&await enterPortal())return}catch(e){}}$('#sessionLoading').classList.add('hidden');$('#loginGate').classList.remove('hidden')}init();
